// @ts-check
/**
 * `npm run fonts`: copies the woff2 subsets of the five families (docs/07 §3, D16) from the @fontsource packages into
 * packages/kit-web/fonts/, copies their SIL Open Font License texts into fonts/LICENSES/, and writes
 * packages/kit-web/src/ui/fonts.css. Only woff2, only the Latin or Arabic subset each family needs, only the weights the
 * design system uses. The apps bundle these files: no request to Google Fonts or any CDN.
 */
import { copyFileSync, existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { ROOT } from "./workspaces.mjs";

const require = createRequire(join(ROOT, "packages/kit-web/package.json"));

/** @type {{ pkg: string, family: string, subset: "latin" | "arabic", weights: number[], use: string }[]} */
export const FONTS = [
  { pkg: "dm-sans", family: "DM Sans", subset: "latin", weights: [400, 500, 700], use: "Latin operations" },
  {
    pkg: "dm-serif-display",
    family: "DM Serif Display",
    subset: "latin",
    weights: [400],
    use: "Latin amounts, titles",
  },
  { pkg: "dm-mono", family: "DM Mono", subset: "latin", weights: [400], use: "references, timers" },
  {
    pkg: "ibm-plex-sans-arabic",
    family: "IBM Plex Sans Arabic",
    subset: "arabic",
    weights: [400, 700],
    use: "Arabic interface; 700 for labels",
  },
  { pkg: "noto-kufi-arabic", family: "Noto Kufi Arabic", subset: "arabic", weights: [700], use: "Arabic display" },
];

const KIT_WEB = join(ROOT, "packages/kit-web");
const OUT = join(KIT_WEB, "fonts");
rmSync(OUT, { recursive: true, force: true });
mkdirSync(join(OUT, "LICENSES"), { recursive: true });

const faces = [];
for (const f of FONTS) {
  const pkgDir = dirname(require.resolve(`@fontsource/${f.pkg}/package.json`));
  copyFileSync(join(pkgDir, "LICENSE"), join(OUT, "LICENSES", `${f.pkg}-OFL.txt`));
  for (const w of f.weights) {
    const file = `${f.pkg}-${f.subset}-${w}-normal.woff2`;
    const src = join(pkgDir, "files", file);
    if (!existsSync(src)) throw new Error(`missing ${src}`);
    copyFileSync(src, join(OUT, file));
    faces.push(
      `/* ${f.family} ${w}, ${f.subset} subset (${f.use}) */\n` +
        `@font-face {\n  font-family: "${f.family}";\n  font-style: normal;\n  font-display: swap;\n  font-weight: ${w};\n` +
        `  src: url("../../fonts/${file}") format("woff2");\n}`,
    );
  }
}

writeFileSync(
  join(KIT_WEB, "src/ui/fonts.css"),
  `/* Generated by tools/scripts/fonts.mjs (npm run fonts). Do not edit. SIL Open Font License: fonts/LICENSES/. */\n\n${faces.join("\n\n")}\n`,
);
console.log(`fonts: ${faces.length} faces written to packages/kit-web/fonts/ and src/ui/fonts.css`);
